[package]
name = "twitter_bot"
version = "0.1.0"
authors = ["Badi Abdul-Wahid <abdulwahidc@gmail.com>"]

[dependencies]
twapi = "0.4.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
restson = "^0.2"
serde = "^1.0"
serde_derive = "^1.0"
