[package]
name = "calculator"
version = "0.1.0"
authors = ["Badi Abdul-Wahid"]
edition = "2018"
# build = "build.rs"

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"
pretty-trait = "0.1"

[build-dependencies.lalrpop]
version = "0.19.0"
features = ["lexer"]
